### ISSUE TITLE
FastCall not processing all samples

### ISSUE THREAD

**Issue by ch728** [PlantGeneticsLab/TIGER#1]
Hi, I am using FastCall to call snps and I am having an issue. I have 384 taxa and two bam files per taxa. When I run FastCall it detects the 768 files, but during the mpileup phase it only processes 192 taxa (384 bam files) and then says it's done with all 384 taxa. In the resulting vcf I only have data for half the samples. See the log and taxaBam_info.txt file attached.
[bam_info.txt](https://github.com/PlantGeneticsLab/TIGER/files/5257475/bam_info.txt)
[fastcall.log](https://github.com/PlantGeneticsLab/TIGER/files/5257477/fastcall.log)

**Comment by Fei-Lu** [comment]
Hi Chris! It works fine on my side. I guess it was because there was some issues with mpileup. Can you write a script to pileup all the 768 files and see if this step is succesful?
